### ISSUE TITLE
stats functions replacements for cpp

### ISSUE THREAD

**Issue by leoisl** [leoisl/GCP#1]
`np.random.negative_binomial` can be replaced by http://www.cplusplus.com/reference/random/negative_binomial_distribution/

`np.random.binomial` can be replaced by http://www.cplusplus.com/reference/random/binomial_distribution/

best replacement I've found for `stats.rankdata()` is https://sites.google.com/site/jivsoft/Home/compute-ranks-of-elements-in-a-c---array-or-vector

**Comment by iqbal-lab** [comment]
These functions already in pandora, right? Can check those

**Comment by leoisl** [comment]
Oh, indeed. Negative binomial used is actually `boost::math::negative_binomial` : https://github.com/leoisl/pandora/blob/16fc4f2bd5b12d5ec4779cbb45343a4a5aeed7d1/src/kmergraphwithcoverage.cpp#L99
I'd prefer to use c++ std lib than adding `boost` as dependency though.

Binomial is actually implemented in the code:
https://github.com/leoisl/pandora/blob/16fc4f2bd5b12d5ec4779cbb45343a4a5aeed7d1/src/kmergraphwithcoverage.cpp#L119-L150

These are also tightly coupled with a pandora data structure (`KmerGraphWithCoverage`), so we have to refactor these functions to be able to use them externally, and independent of `KmerGraphWithCoverage`. 

I guess using the cpp std function might be easier and faster?

We still did not need to use sth like `stats.rankdata()`  in `pandora`, so we don't have it there.

**Comment by leoisl** [comment]
Due to https://github.com/leoisl/GCP/issues/6, only stats function needed now is stats.rankdata()
