### ISSUE TITLE
Make this library NOT responsible for simulating and genotyping, but just GCP computation

### ISSUE THREAD

**Issue by leoisl** [leoisl/GCP#6]
One option is to ask the client itself to simulate and genotype, and having GCP be responsible only for producing a mapping between conf and percentile, and capacity to interpolate for confs it has not seen before. The problem is that simulations should be closely coupled to genotyping, and each tool can be very particular on how they genotype

**Comment by mbhall88** [comment]
Given that we want to eventually move towards a centralised "unified" genotyping approach, I would vote for having the simulations handled by this library. Costs a bit of work/time now but saves a lot more work/time in total in the long run.

However, I guess it depends on @iqbal-lab's idea for what he wanted the scope of this library to be...

**Comment by leoisl** [comment]
Unified genotyper should also be able to compute Genotype Confidence Percentile and to (obviously) genotype. So, unified genotyper actually should do everything this library should do, and lots of more stuff... Maybe we could evolve this into the unified genotyper later? ... Are there any other libraries we want to do which has overlaps with this one?

**Comment by iqbal-lab** [comment]
There are structural reasons why a unified genotyper is not easy.
Gramtools has data structures that integrally maintain a hierarchy, and store equivalence class info in mapping. pandora builds from a similar PRG, but once we get to the kmer graph we've lost that hierarchy, so we'd need to work to get similar info from quasimapping. 
Pandora is much more aware of the max-likelihood path, both per sample and when you do compare. I think we'll evolve to something that learns from both, which could be a UG, but we have some big chunks of work in the interim - all of michael's TB work, brice's surface antigen plasmodium stuff and his mixtures.

 i don't think it makes sense to create the UG now. I see these projects (pandora, gramtools) as iteratively testing and proving ideas, over long timescales (years already, more to come). pandora is close to proving the value of prgs, and showing how the pandora-compare approach makes a difference. Having done that, make-prg and TB work will dominate for months. Gramtools is on the way to showing how hierarchical genotyping of nesting is a good idea, but it will get messy with mixtures and we may change our ideas. So i don't think we have a clear path to a combined genotyper yet. 

I vote client does simulation and genotyping at the moment, happy to discuss further

**Comment by iqbal-lab** [comment]
How do you feel about this folks? i have two covid calls tomorrow afternoon, but i suspect they won't use the full hours, could talk more tomorrow if you want? @bricoletc ?

**Comment by leoisl** [comment]
> I vote client does simulation and genotyping at the moment, happy to discuss further

I am happy and agree with this. In an ideal world, we would like GCP/UG to deal with everything for us (simulation, genotyping, percentiler), but this is too large of a leap. I prefer this approach, which is a smaller step, but it is clearly achievable technically now. We can redesign these dependencies/components later, and maybe move to a more complete library or maybe conclude it is too hard, and it will be a lot easier to take this decision if we look at pandora and gramtools simulation and genotyping code together, and try to factor out the commonalities

**Comment by bricoletc** [comment]
yep, i agree

**Comment by leoisl** [comment]
Ok, it seems we are good!
